name: GitHub Pages Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Navigate to the project directory before running npm commands
      - name: Navigate to project directory
        run: cd susimage

      # We need to run all subsequent commands in the susimage directory
      - name: Install Dependencies
        working-directory: ./susimage
        run: npm install

      - name: Create env file
        working-directory: ./susimage
        run: |
          echo "NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=${{ secrets.NEXT_PUBLIC_UNSPLASH_ACCESS_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_REPLICATE_API_TOKEN=${{ secrets.NEXT_PUBLIC_REPLICATE_API_TOKEN }}" >> .env.local

      - name: Build Project
        working-directory: ./susimage
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./susimage/out
          force_orphan: true